language: php

notifications:
  on_success: never
  on_failure: change

php:
  - 5.4
  - 5.5
  - 5.6
  - 7.0

env:
  - WP_VERSION=4.8 WP_MULTISITE=0
  - WP_VERSION=4.8 WP_MULTISITE=1
  - WP_VERSION=latest WP_MULTISITE=0
  - WP_VERSION=latest WP_MULTISITE=1
 
before_script:
  - composer install --no-interaction
  
script:
   - vendor/bin/phpcs -n --report=emacs --standard=phpcs.ruleset.xml class-home-url-replace.php
